language: ruby
# only run CI-builds on build branch
branches:
  only:
  - build
rvm:
- 2.6.3
# set execution permission on our build script
before_script:
 - chmod +x ./script/build.sh
# path to our build script. 
# Travis will run `bundle install` by default before running our script
script: ./script/build.sh
# install: gem install jekyll html-proofer
# script: bundle exec jekyll build
exclude: [vendor]
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false